name: pasabahce
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  pin_code_fields: ^7.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/
    - assets/images/icons/
    - assets/images/categories/
    - assets/images/top_deals/
    - assets/images/featured_products/
    - assets/images/search_by_brand/
    - assets/images/bottom_navigation_bar/
    - assets/images/details/

